# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goji < Formula
  desc "goji binaries for brew."
  homepage "https://github.com/sanriodev/goji"
  version "1.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sanriodev/goji/releases/download/v1.2.1/goji_1.2.1_darwin_amd64.tar.gz"
      sha256 "0f6ef905234c7e07ec5abfc2a816eba92ce1d5abaf82cf1c9db36250210340d4"

      def install
        bin.install "goji"
      end
    end
    on_arm do
      url "https://github.com/sanriodev/goji/releases/download/v1.2.1/goji_1.2.1_darwin_arm64.tar.gz"
      sha256 "b89820926fe7fdee4e376dd51a359acd750a6e62fed3227f8aaa2e4440ac21e9"

      def install
        bin.install "goji"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanriodev/goji/releases/download/v1.2.1/goji_1.2.1_linux_amd64.tar.gz"
        sha256 "152372fd7209b8fcf4f1247eac290be427816264bfdac3a8e255f38ce785b765"

        def install
          bin.install "goji"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanriodev/goji/releases/download/v1.2.1/goji_1.2.1_linux_arm64.tar.gz"
        sha256 "1e2dd11c7a7e83c3c6cf0da543332523b56fcfb27c3db31212b292284edceeab"

        def install
          bin.install "goji"
        end
      end
    end
  end
end
