# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goji < Formula
  desc "Lightweight version of Oji text emoticon generator. Rewritten in go"
  homepage "https://github.com/sanriodev/goji"
  version "1.4.3-3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sanriodev/goji/releases/download/v1.4.3-3/goji_1.4.3-3_darwin_amd64.tar.gz"
      sha256 "e9e43263fef0fb9309987349d6b58f2075a63ed059f124e530d757d9776f942d"

      def install
        bin.install "goji"
      end
    end
    on_arm do
      url "https://github.com/sanriodev/goji/releases/download/v1.4.3-3/goji_1.4.3-3_darwin_arm64.tar.gz"
      sha256 "c12d96a64e3cc614162dd857bb0814ee91b63886d8cd3673ee5846a210ce4dde"

      def install
        bin.install "goji"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanriodev/goji/releases/download/v1.4.3-3/goji_1.4.3-3_linux_amd64.tar.gz"
        sha256 "10497a5f2cb71ed550243385b34eb874768d9489e54936c8167d920a27218f0a"

        def install
          bin.install "goji"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanriodev/goji/releases/download/v1.4.3-3/goji_1.4.3-3_linux_arm64.tar.gz"
        sha256 "23fbdedc9a0f2836d98208f686f100f459be0e5f9445da8254382f4582dc76bb"

        def install
          bin.install "goji"
        end
      end
    end
  end

  test do
    output = shell_output("#{bin}/goji -h")
    assert_match(/Create custom or random text emojis/, output)
    assert_match(/--new/, output)
    assert_match(/--random/, output)
  end
end
