# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goji < Formula
  desc "Lightweight version of Oji text emoticon generator. Rewritten in go"
  homepage "https://github.com/sanriodev/goji"
  version "1.4.3-2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sanriodev/goji/archive/refs/tags/v1.4.3-2.tar.gz"
      sha256 "102e020726f8e56ff83b83dce3d87b0a58bd57d05891b7100c07bb689af2004a"

      def install
        system "go", "build", *std_go_args
      end
    end
    on_arm do
      url "https://github.com/sanriodev/goji/archive/refs/tags/v1.4.3-2.tar.gz"
      sha256 "bd846f6da60c111d7b12f5ef05283a0664b1ff40faf5fddb6965f2797ab34bf6"

      def install
        system "go", "build", *std_go_args
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanriodev/goji/archive/refs/tags/v1.4.3-2.tar.gz"
        sha256 "2bf996ffbd162127e251efcf03fa30ff7c4fac458a22453589ec6b370258bf2d"

        def install
          system "go", "build", *std_go_args
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sanriodev/goji/archive/refs/tags/v1.4.3-2.tar.gz"
        sha256 "e30e10b2b8c24c8f25d3a9b2fda70d6f855d091da65fb7ed3130791735984e28"

        def install
          system "go", "build", *std_go_args
        end
      end
    end
  end

  test do
    output = shell_output("#{bin}/goji -h")
    assert_match(/Create custom or random text emojis/, output)
    assert_match(/--new/, output)
    assert_match(/--random/, output)
  end
end
